### Add John Doe
POST http://localhost:3000/api/employees/add
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "gender": "Male",
  "department": "Engineering",
  "salary": 50000
}

### Add Jane Smith
POST http://localhost:3000/api/employees/add
Content-Type: application/json

{
  "name": "Jane",
  "surname": "Smith",
  "gender": "Female",
  "department": "Marketing",
  "salary": 60000
}

### Add Michael Brown
POST http://localhost:3000/api/employees/add
Content-Type: application/json

{
  "name": "Michael",
  "surname": "Brown",
  "gender": "Male",
  "department": "Finance",
  "salary": 55000
}

### Add Emily Davis
POST http://localhost:3000/api/employees/add
Content-Type: application/json

{
  "name": "Emily",
  "surname": "Davis",
  "gender": "Female",
  "department": "Engineering",
  "salary": 65000
}

### Add Anna Wilson
POST http://localhost:3000/api/employees/add
Content-Type: application/json

{
  "name": "Anna",
  "surname": "Wilson",
  "gender": "Female",
  "department": "Marketing",
  "salary": 62000
}

### Get All Employees
GET http://localhost:3000/api/employees/view
Content-Type: application/json

### Get Employees by Department - Engineering
GET http://localhost:3000/api/employees/Engineering
Content-Type: application/json

### Get Employees by Department - Marketing
GET http://localhost:3000/api/employees/Marketing
Content-Type: application/json

### Get Employees by Department - Finance
GET http://localhost:3000/api/employees/Finance
Content-Type: application/json

### Update John Doe's Salary
PUT http://localhost:3000/api/employees/666879575121b59963127399
Content-Type: application/json

{
  "salary": 55000
}

### Delete Employee - John Doe
DELETE http://localhost:3000/api/employees/66879575121b59963127399
Content-Type: application/json
